# https://docs.docker.com/compose/compose-file/
version: '3.8'
services:
  db:
    image: postgres:13.0
    restart: always
    volumes:
      - db-data0:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  db-data0:
